# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/FirstParameterIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
